### ISSUE TITLE
Investigate moving documentation to ReadTheDocs

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/lephare-dev#11]
Currently there is a make docs command that will generate a PDF. We need to investigate how to port the information to ReadTheDocs. 

Also worth investigating is whether the Sphinx code that created autodocs from python docstrings will do the same for C++ docstrings/comments.

**Comment by drewoldag** [comment]
Also note that there seems to be some hard coded paths in the notebooks. For those to be rendered correctly in the documentation, we'll need to address that. 

See the first cell here: https://github.com/lincc-frameworks/lephare-dev/blob/main/docs/notebooks/Building_list_of_onesources.ipynb

**Comment by johannct** [comment]
yes it is the same story as mentioned elsewhere, about these 2 basic env var that LePHARE has been depending on : LEPHAREDIR and LEPHAREWORK : the first one needs to point to the root directory, or in case of binary install, to the directory where needed files are located, and LEPHAREWORK points to an arbitrary place where intermediary and final outputs are located.

**Comment by drewoldag** [comment]
To make a navigable hierarchy programmatically, we need to use `Exhale` (https://exhale.readthedocs.io/en/latest/index.html) in combination with `Breathe`. The PR linked to this issue shows how they are used together. 

Roughly speaking the documentation should start to look something like this: 

<img width="568" alt="Screen Shot 2024-03-19 at 3 58 35 PM" src="https://github.com/lincc-frameworks/lephare-dev/assets/47493171/6e254878-3321-4810-b399-5072866b85e5">
