### ISSUE TITLE
Confirm Notebooks run in new setup

### ISSUE THREAD

**Issue by jeremykubica** [lincc-frameworks/lephare-dev#19]
Confirm that all of the notebooks run properly in the gitlab code organization. Requires #7 that the Python code to be imported first.

**Comment by drewoldag** [comment]
I ran through all the notebooks and found that they all seem to work on some level. This indicates that the work that we did to port from the gitlab repo to the github repo didn't break anything. I've outlined what I found below.

*Needs work*
`building_list_of_onescource.ipynb` having trouble in 4th cell, `PhotoZ` "Library doesn't exist"?
`examples.ipynb` this notebook has some cells that run, but mostly broken.

*One small error*
`Testing_fit_of_one_object_of_the_catalogue.ipynb` mostly works, references onesource.errors that doesn't seem to exist. 

*Running pretty well after updating hard coded directories*
`example_full_run.ipynb` works well after including LEFPHAREDIR and LEPHAREWORK.
`Example_of_usage_of_magSvc.ipynb` works well after including LEFPHAREDIR and LEPHAREWORK.
`intro.ipynb` works well after including LEFPHAREDIR and LEPHAREWORK.

**Comment by drewoldag** [comment]
I'll try to get a PR together that implements some of the small fixes to the directory structures. But I believe all the notebooks depend on at least some of data that is not currently included in the repository. 

Additionally, we should review the notebooks for consistency, remove notebooks that are expired, and make sure that when specific files are referenced, that those files are in a consistent directory.

**Comment by drewoldag** [comment]
PR #40 addresses the changes needed in:

- example_full_run.ipynb 
- Example_of_usage_of_magSvc.ipynb 
- intro.ipynb
