### ISSUE TITLE
Convert the gitlab action to a github action

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/lephare-dev#9]
It seems that there may just be one, but do a thorough examination of the gitlab repo to make sure. 

I only found .../scripts/CI/build.sh and .../test/ci_test.sh. There may be more that are scattered around.

**Comment by johannct** [comment]
So this is almost done, the only thing remaining I believe, is to actually add testing to the actions.

**Comment by drewoldag** [comment]
Looks like all the work that is happening in `.../scripts/CI/build.sh` is being covered by the existing github CI. The only remaining task is to ensure that we've pulled over all the tests from the gitlab repo. I believe that the only remaining test is `test_filter.py`. 

Looking at this page (https://gitlab.lam.fr/Galaxies/LEPHARE/-/jobs) it seems like only build.sh was being used for CI in gitlab. I could be missing something since I'm not familiar with gitlab. @johannct could you double check? 

If build.sh is the only CI test in gitlab, then I think we're basically finished. If gitlab is running co_tests.sh somewhere, then we should put together a quick github action for that.

**Comment by johannct** [comment]
This is correct : build.sh was the only one running. The other one, test/ci_test.sh was put up to anticipate a real case test in CI, say before cutting a tag. But I never took the time to actually add it to the CI. Note that it is equivalent to tests/test_suite.sh

**Comment by drewoldag** [comment]
So given that comment @johannct do you feel that we need to get a CI action running that will run test/ci_test.sh? Or are we in a place now where we can close out this issue?

**Comment by johannct** [comment]
ah no, this is a real validation test, not a unit test. It uses real data and does real stuff, so until we have the ancillary file machinery set up we cannot do anything with it.

**Comment by johannct** [comment]
so the PR can go, sure.
